# Generated by Django 3.1.7 on 2021-05-12 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.URLField(max_length=500)),
                ('shortened_link', models.CharField(blank=True, default=None, max_length=20, null=True, unique=True)),
                ('clicks', models.IntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
